% Choose the integral scheme
% 1 for HDO(harmonious diffusion operator)
% 2 for 4th order Runge-Kutta
% 3 for Predict Correct
% 4 for leap frog
function [tau_n,U_np1,V_np1,Z_np1,LU,LV,LZ] = integrator(pass,time_step,IntSch,nt,...
                                                         U_nm1,V_nm1,Z_nm1,LU_nm1,LV_nm1,LZ_nm1,...
                                                         U,V,Z,dlambda,dtheta,a,Omega,g,...
                                                         lat_u,lat_v,lat_z,...
                                                         nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                                                         coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y)
if IntSch==1
    [tau_n,U_np1,V_np1,Z_np1,LU,LV,LZ] = HDO(pass,time_step,...
                                             U,V,Z,dlambda,dtheta,a,Omega,g,...
                                             lat_u,lat_v,lat_z,...
                                             nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                                             coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y);
elseif IntSch==2
    [tau_n,U_np1,V_np1,Z_np1,LU,LV,LZ] = RK4(pass,time_step,...
                                             U,V,Z,dlambda,dtheta,a,Omega,g,...
                                             lat_u,lat_v,lat_z,...
                                             nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                                             coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y);
elseif IntSch==3
    [tau_n,U_np1,V_np1,Z_np1,LU,LV,LZ] = PC(pass,time_step,...
                                            U,V,Z,dlambda,dtheta,a,Omega,g,...
                                            lat_u,lat_v,lat_z,...
                                            nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                                            coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y);
elseif IntSch==4
    [tau_n,U_np1,V_np1,Z_np1,LU,LV,LZ] = LF(pass,time_step,nt,...
                                            U,V,Z,...
                                            U_nm1,V_nm1,Z_nm1,LU_nm1,LV_nm1,LZ_nm1,...
                                            dlambda,dtheta,a,Omega,g,...
                                            lat_u,lat_v,lat_z,...
                                            nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                                            coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y);
end