% Choose the spatial discrete scheme for split
% pass = 0 for the full L_operator
% pass = 1 for the fast pass operator
% pass = 2 for the slow pass operator
function [LU,LV,LZ] = spatial_discrete(pass,U,V,Z,dlambda,dtheta,a,Omega,g,lat_u,lat_v,lat_z,...
                                       nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                                       coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y)
                             
if pass == 0
    [LU,LV,LZ] = L_operator(U,V,Z,dlambda,dtheta,a,Omega,g,lat_u,lat_v,lat_z,...
                            nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                            coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y);
elseif pass == 1
    [LU,LV,LZ] = fast_pass(U,V,Z,dlambda,dtheta,a,Omega,g,lat_u,lat_v,lat_z,...
                           nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                           coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y);
elseif pass == 2
    [LU,LV,LZ] = slow_pass(U,V,Z,dlambda,dtheta,a,Omega,g,lat_u,lat_v,lat_z,...
                           nx_u,ny_u,nx_v,ny_v,nx_z,ny_z,...
                           coefU_x,coefU_y,coefV_x,coefV_y,coefZ_x,coefZ_y);
end